Menu improvements
NativePHP/laravel pull request #423
Opened 2024-11-20 03:09 UTC by simonhamp

**Heads up, this introduces some significant breaking changes!**

We've been discussing internally for a while how the Menu API sucks a little. There are a few quirks, it doesn't really expose the stuff you probably want, and it just feels awkward, it doesn't feel very "Laravel".

So this is my attempt to improve that by:

- Introducing a new `Menu` facade which wraps a new `MenuBuilder` class
    This menu builder let's you access the underlying `MenuItem` objects more easily and build your menus with a more expressive DX. More on this in a moment
- More `MenuItem` types that map to standard OS functions (called `Roles`)
- A `GoToUrl` menu item type that can change the currently-focused window's URL onclick without any extra wiring
- Submenus are now definable in a more expressive way
- A new `default` helper to create the default menu even more easily
- Enhanced event data coming back from menu item clicks, such as combo keys and item IDs (if you provided one when creating the menu)
- And you can now update the menu entirely after you've created it! 💪🏼

## Define the default menu

### Before
```php
use Native\Laravel\Menu\Menu;

Menu::new()
    ->appMenu()
    ->editMenu()
    ->viewMenu()
    ->windowMenu()
    ->register();
```

### After
```php
use Native\Laravel\Facades\Menu;

Menu::default();
```

## Define a custom menu

### Before
```php
use Native\Laravel\Menu\Menu;

Menu::new()
    ->appMenu()
    ->submenu(
        'My Submenu',
        Menu::new()
            ->link('https://nativephp.com', 'Documentation')
    )
    ->register();
```

### After
```php
use Native\Laravel\Facades\Menu;

Menu::create(
    Menu::app(),
    Menu::make(
        Menu::link('https://nativephp.com')
            ->label('Documentation'),
        // or: Menu::link('https://nativephp.com', 'Documentation'),
    )->label('My Submenu'),
);
```

`Menu::make()` returns a `Native\Laravel\Menu\Menu` instance. Many of the other helpers return a `MenuItem` subclass, from which you can chain calls to their other methods.

This gives you far more control over your menus. Building your menus has never been more straightforward.

2024-11-22 20:01 UTC, SRWieZ requested changes
It's quite a change in syntax, but I believe this PR improves it.  
-  Some docblocks are incorrect or "incomplete"
-  I prefer using "hotkey" instead of "accelerator."  
- I got a bug with my event on a menu throwing an exception because of a missing named argument on my constructor. I think we should either ask devs to extend `MenuItemClicked` with their event or better create a contract that they should implement with the following constructor: `public function __construct(public array $item, public array $combo = [])`

Overall it's great!

Also we should add a note in the documentation stating that we cannot change the name of the first menu in macOS.  This tweet examples does not work, always returns the name of the app:
```php  
Menu::create(Menu::edit())  
```  
```php  
Menu::create(Menu::make()->label('My label'))  
```  

<img width="465" alt="Capture d’écran 2024-11-22 à 20 41 33" src="https://github.com/user-attachments/assets/342d026e-488d-4f79-adf9-4ce98ef1c29e">

2024-11-22 22:18 UTC, gwleuverink commented
Honestly this works great! I've tinkered with it a bit now. 

One thing I might be missing. Context menu's were mentioned. Is it possible to trigger a menu on a button click? This doesn't work right now and could be a cool addition.

I've got a alpine magic I use for this right now. I'm happy to extract that to the Native helper if you want.

Right now it looks like this:

``` blade

<button
    type="button"
    x-on:click="
        $contextMenu([
            new MenuItem({
                label: 'Foo',
            }),
            new MenuItem({
                label: 'Bar',
            }),
        ])
    "
>

```

It does involve adding the MenuItem class to the window scope. But that can be namespaced under the Native helper if needed. 

I haven't tested this, but it might be feasible to add this to the php api instead. The code is pretty slim.

2024-11-22 22:22 UTC, gwleuverink commented
Extracted to the Native helper I imagine something like this:

``` blade
<button
    type="button"
    onclick="Native.contextMenu([
        new MenuItem({
            label: 'Foo',
        }),
        new MenuItem({
            label: 'Bar',
        }),
    ])"
>
```

2024-11-22 22:51 UTC, gwleuverink commented
> It does involve adding the MenuItem class to the window scope. But that can be namespaced under the Native helper if needed.

Turns out using `Menu.buildFromTemplate` I can construct this menu from a array of plain objects

2024-11-23 18:20 UTC, simonhamp commented
@gwleuverink that context menu stuff looks super cool! Fancy wrapping whatever you've needed to modify there into a new PR?

2024-11-24 03:27 UTC, gwleuverink commented
> @gwleuverink that context menu stuff looks super cool! Fancy wrapping whatever you've needed to modify there into a new PR?

Done! https://github.com/NativePHP/electron/pull/140

2024-12-01 22:55 UTC, simonhamp commented on src/Facades/Menu.php
> + * @method static \Native\Laravel\Menu\Menu make(MenuItem ...$items)
```suggestion
 * @method static \Native\Laravel\Menu\Menu make(\Native\Laravel\Menu\Items\MenuItem ...$items)
```

2024-12-01 22:59 UTC, simonhamp commented on src/Facades/Menu.php
> + * @method static Link link(string $url, string $label = null, ?string $hotkey = null)
Ah, I think you mean in the `MenuItem` class, but the Facade instantiates the `MenuBuilder` - there it is called `$hotkey`.

I'm not going to change the `MenuItem` class, as that maps more closely to the underlying Electron implementation and feels clearer as `$accelerator` to me in that context.

I prefer to create an alias, per your next point

2024-12-01 23:02 UTC, simonhamp commented on src/Events/Menu/MenuItemClicked.php
> +    public function __construct(public array $item, public array $combo = []) {}
This comes straight from Electron and I don't want the docblock structure to be wrong if/when they change things, as that would be more confusing imo. Perhaps at some point we create our own abstraction around this? 🤷🏻‍♂️

2024-12-01 23:38 UTC, merged