fix: child process cmd: option except iterable array
NativePHP/laravel pull request #429
Opened 2024-11-21 23:10 UTC by SRWieZ

I encountered an error that was not understandable at first glance.
TypeScript was compiling that cmd: was not iterable.

This error was crashing the app before even showing a window.

For context, I was writing this  
```php
ChildProcess::artisan(cmd: ['app:victron-mqtt','--vrmid' => 'myvrmid'], alias: 'something');
```

instead of  
```php
ChildProcess::artisan(cmd: ['app:victron-mqtt','--vrmid=myvrmid'], alias: 'something');
```

Did you notice the difference?

-----
Screenshot of the error:  
<img width="1074" alt="Capture d’écran 2024-11-21 à 23 49 58" src="https://github.com/user-attachments/assets/7210c2ac-d64e-4f20-bf05-b6c07b190fe9">

2024-11-21 23:17 UTC, SRWieZ commented
Oh, and I apologise for the branch names. 

I make quick fixes by directly modifying files in my vendor directory and using the web version of GitHub for the PR 🙈 

I find this method faster when it only involves one file in one repo. 

This allows me to report and fix bugs while staying focused on my apps 😄

2024-11-22 11:19 UTC, simonhamp requested changes
Interesting! I think what you've bumped into is that as a Laravel/PHP dev, our expectation is that a command's parameters are a keyed array, which I think is actually a good interface and pretty common across other PHP libraries that do something similar.

But Electron's `utilityProcess` expects [a flat JS array of strings](https://www.electronjs.org/docs/latest/api/utility-process#utilityprocessforkmodulepath-args-options) (i.e. a list).

I'm not sure simply wrapping in `array_values` is enough here... devs may find the fact that they can't use named array items unusual and even confusing/frustrating that some of their command definition is completely ignored.

I think we could do one of a couple of things, either:

- Accept the args as a hash table (assoc. array) and do the work to flatten the keys onto their values _before_ sending to Electron, so that...
    ```php
    ['app:some-command', '--arg1' => 'val', '--arg2' => 'val']
    // Becomes
    ['app:some-command', '--arg1=val', '--arg2=val']
    ```
- Add an exception when we see an associative array and update the docs to explicitly state that the command must be a flat array such that:
    ```php
    ['app:some-command', '--arg1' => 'val', '--arg2' => 'val'] // => throws new ChildProcessException
    ['app:some-command', '--arg1=val', '--arg2=val'] // succeeds
    ```

I honestly don't mind whichever of these approaches we go for

2024-11-22 20:49 UTC, gwleuverink commented
I'm down to support this associative syntax. I touched it when adding mixed string|array parameters. 

Laravel's process facade doesn't support it (and doesn't throw an exception)
So an argument for syntax parity could be made as wel

``` php 
$result = Illuminate\Process::run(['app:some-command', '--arg1' => 'val', '--arg2' => 'val']);

$result->command(); // "'app:some-command' 'val' 'val'"
```

2024-11-22 21:09 UTC, gwleuverink commented
Another note. Now I've thought about it a bit more.

Some commands don't adhere to this syntax (using an `=` sign). As I understand it this is up to the programmer writing the command.

So both of these could be valid depending on the program: `--arg=param or --arg param`

Taking that into consideration I'm leaning towards sticking to only flat arrays & add the Exception for good measure.

2024-11-22 21:15 UTC, SRWieZ commented
> @simonhamp: Interesting! I think what you've bumped into is that as a Laravel/PHP dev, our expectation is that a command's parameters are a keyed array, which I think is actually a good interface and pretty common across other PHP libraries that do something similar.

I'm not sure, I may have invented it. 
Neither Symphony nor Laravel supports this, and I have never used any others.

> @simonhamp: I honestly don't mind whichever of these approaches we go for

Something I agree with you, this current implement feels like a soft fail. 

> @gwleuverink: Taking that into consideration I'm leaning towards sticking to only flat arrays & add the Exception for good measure.

Me too. I'm gonna implement it right now.

2024-11-23 00:15 UTC, simonhamp commented
> Neither Symphony nor Laravel supports this, and I have never used any others.

No way. I could've sworn I've also done this in Laravel... my LLM cells are hallucinating

2024-11-23 00:18 UTC, simonhamp approved these changes

2024-11-23 10:27 UTC, merged

2024-11-23 10:27 UTC, SRWieZ commented
I propose a middle ground.

1. Instead of checking at runtime by comparing `array_keys` to a `range` (https://github.com/NativePHP/laravel/pull/429/commits/e07c964fbbaf0515c8025204e18400dcd664ba8f), kind of weird.
2. I suggest using `array_values` and adding a hint for static analyzers and IDEs to indicate that an indexed array of strings is expected (https://github.com/NativePHP/laravel/pull/429/commits/539e87505e367fe2adec5e7f893267cb52bc9d81)

Vote, one or two. I vote 2.

2024-11-23 10:27 UTC, SRWieZ commented
Og, vote ended, it's merged 🤣

2024-11-23 10:45 UTC, SRWieZ commented
>Sorry, I thought it was done already... might be best to move back into draft if you're still rocking on it

My bad. 

> On this basis, I'd shoot for whatever ends up being the most consistent with current behaviour elsewhere - if that is just array_values, then that's fine

At the last minute, I thought I might have a better solution that aligns with other libraries and helps the developer avoid mistakes. 

I hope you're okay with the final change.